FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod tidy
COPY . .
RUN go install github.com/golang-migrate/migrate/v4/cmd/migrate@latest
FROM alpine:latest
RUN apk add --no-cache postgresql-client
COPY --from=builder /go/bin/migrate /usr/local/bin/migrate
WORKDIR /app
CMD ["migrate"]